# Setup
title: 小叶不是叶
description: 小叶不是叶的小树
url: https://shengyexiuyo.org.edu.kg
avatar: /assets/img/me.png
paginate: 5
permalink: pretty
cover_image: /assets/img/bg.jpeg
timezone: +0000


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

include:
  - _pages
  
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts/

# Optimize Jekyl SEO Tag
twitter:
  username: shengye
  card: summary
logo: me.png
social:
  name: shengye
  links:
    - https://twitter.com/
    - https://github.com/shengye2413
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: 

# Replace this value and uncomment to enable Disqus
disqus: shengye

# Specify the author for blog posts
author:
  name: shengye
  url: https://github.com/shengye2413/
  email: shengyexiuyo2413@gmail.com

remote_theme: vszhub/not-pure-poole
